spring.application.name=risk-service
server.port=8084
medilabo.patient.url.api=${MEDILABO_PATIENT_URL_API:http://localhost:8081}
medilabo.note.url.api=${MEDILABO_NOTE_URL_API:http://localhost:8083}
# API REST .....................................................................
# Ne pas exposer les details des erreurs.
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
# desactiver la page HTML des erreurs.
server.error.whitelabel.enabled=false

LOG .....................................................................................
logging.level.org.springframework=INFO
logging.level.root=info
#logging.level.root=debug
#appliquer a toutes les classes de mon package.
#   info : Affiche les messages de niveau info, warn, et error.
#   error : Affiche uniquement les messages de niveau error.
#   debug : Affiche les messages de tous les niveaux : debug, info, warn, et error.
#logging.level.com.medilabo.risk_service=info
#logging.level.com.medilabo.risk_service=error
logging.level.com.medilabo.risk_service=debug

# SECURITY .................................................................................
security.api.username=${MEDILABO_API_USERNAME}
security.api.password=${MEDILABO_API_PASSWORD}
