spring.application.name=gateway-service

# API REST .....................................................................
# Ne pas exposer les details des erreurs.
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
# desactiver la page HTML des erreurs.
server.error.whitelabel.enabled=false

