server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # très important car j'ai la version mvc et non flux.
      mvc:
        routes:
          # ---------- Patients ----------
          - id: patient-service
            uri: ${MEDILABO_PATIENT_URL_API:http://patient-service:8081}
            predicates:
              - Path=/api/patients/**
            filters:
              # /api/patients/...  ->  /patients/... pour le backend
              - StripPrefix=1
          # ---------- Notes ----------
          - id: note-service
            uri: ${MEDILABO_NOTE_URL_API:http://note-service:8083}
            predicates:
              - Path=/api/notes/**
            filters:
              # /api/notes/...  ->  /notes/... pour le backend
              - StripPrefix=1
          # ---------- Risk ------------
          - id: risk-service
            uri: ${MEDILABO_RISK_URL_API:http://risk-service:8084}
            predicates:
              - Path=/api/risk/**
            filters:
              # /api/risk/...  ->  /risk/... pour le backend
              - StripPrefix=1
                                    
logging:
  level:
    # pour voir les détails du routing.
    org.springframework.cloud.gateway: DEBUG
    # pour voir les requêtes entrantes, les erreurs.
    org.springframework.web: DEBUG
security:
  api:
    username: ${MEDILABO_API_USERNAME}
    password: ${MEDILABO_API_PASSWORD}
