spring.application.name=webapp
server.port=8082
# ici, on met l'URL de la gateway et non l'URL des microservices Patient ou Note ou Risk
medilabo.url.api=${MEDILABO_URL_API:http://localhost:8080/api}

# API REST .....................................................................
# Ne pas exposer les details des erreurs.
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
# desactiver la page HTML des erreurs.
server.error.whitelabel.enabled=false
# pour intercepter la 404 (route inconnue) dans GlobalExceptionHandler :
#   Laisse Spring lever une exception ce cas de figure.
spring.mvc.throw-exception-if-no-handler-found=true
#   Desactive le mapping des ressources statiques par defaut (sinon cela ne fonctionne pas).
spring.web.resources.add-mappings=false

 LOG .....................................................................................
logging.level.org.springframework=INFO
logging.level.root=info
#logging.level.root=debug
#appliquer a toutes les classes de mon package.
#   info : Affiche les messages de niveau info, warn, et error.
#   error : Affiche uniquement les messages de niveau error.
#   debug : Affiche les messages de tous les niveaux : debug, info, warn, et error.
#logging.level.com.medilabo.webapp=info
#logging.level.com.medilabo.webapp=error
logging.level.com.medilabo.webapp=debug

# SECURITY .................................................................................
security.api.username=${MEDILABO_API_USERNAME}
security.api.password=${MEDILABO_API_PASSWORD}

